/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tarifas;

import Clientes.Interfaces;
import Clientes.MClientes;
import Conector.Conector;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elvis
 */
public class Tarifas extends javax.swing.JFrame {
 Conector con = new Conector();
    Connection cn = con.getConexion();
    String aux="0";
    static ResultSet res;
    public Tarifas() throws SQLException {
        initComponents();
        CargarDatos();
    }
    public void CargarDatos() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) VarTabla.getModel();
        modelo.setRowCount(0);
        res = Conector.Consulta("select * from Tarifa");

        try {
            while (res.next()) {
                Vector v = new Vector();
                aux=res.getString(1);
                v.add(res.getString(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                modelo.addRow(v);
                VarTabla.setModel(modelo);
            }
            System.out.println(aux);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo establecer la conexion" + e.getMessage(), "Error de Conexion", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VarTabla = new javax.swing.JTable();
        txtTipo = new javax.swing.JTextField();
        txtTarifa = new javax.swing.JTextField();
        BInsert = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        VarTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Tipo de Tarifa", "Valor Tarifa"
            }
        ));
        jScrollPane1.setViewportView(VarTabla);

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        BInsert.setText("Insertar");
        BInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsertActionPerformed(evt);
            }
        });

        BModificar.setText("Modficar");
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre de Tarifa:");

        jLabel2.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BModificar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(42, 42, 42)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BInsert)
                            .addComponent(BModificar))))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsertActionPerformed

        try {
           if(txtTipo.getText().equals("")||txtTarifa.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Debes ingresar valores a insertar", "Advertencia", JOptionPane.WARNING_MESSAGE);
           }else{
 
            PreparedStatement pps = cn.prepareStatement("INSERT INTO Tarifa(idtarifa,tipotarifa,valortarifa) VALUES(?,?,?)");
            
            pps.setString(1, Integer.toString(Integer.parseInt(aux)+1));
            pps.setString(2, txtTipo.getText());
            pps.setString(3, txtTarifa.getText());
               System.out.println(aux);
            JOptionPane.showMessageDialog(null, "Datos Guardados");
            int res = pps.executeUpdate();
            if (res < 0) {
                JOptionPane.showMessageDialog(null, "Error al ingresar");
            }
           }
        } catch (Exception e) {
            System.out.println(e);
        }
     try {
         CargarDatos();       // TODO add your handling code here:
     } catch (SQLException ex) {
         Logger.getLogger(Tarifas.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_BInsertActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
try {
            int filsel = VarTabla.getSelectedRow();
            String num = VarTabla.getValueAt(filsel, 0).toString();
            if (filsel == -1) {
                JOptionPane.showMessageDialog(null, "Debes seleccionar el cliente a modificar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                if(txtTipo.getText().equals("")||txtTarifa.getText().equals("")){
                     JOptionPane.showMessageDialog(null, "Debes ingresar valores a modificar", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }else{
            PreparedStatement pps = cn.prepareStatement("update Tarifa set tipotarifa=?,valortarifa=? where idTarifa="+num);
                    System.out.println(num);
            pps.setString(1, txtTipo.getText());
            pps.setString(2, txtTarifa.getText());
            JOptionPane.showMessageDialog(null, "Datos Guardados");
            CargarDatos();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione el cliente a modificar");
        }
        
       
    }//GEN-LAST:event_BModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarifas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tarifas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tarifas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInsert;
    private javax.swing.JButton BModificar;
    private javax.swing.JTable VarTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
